# Javascript Node CircleCI 2.0 configuration file
# YAML Passer - https://yaml-online-parser.appspot.com/
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
   # The build job
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
        - run: npm install
        - save_cache:
              paths:
                  node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm test

  deploy_prod_dev:
    working_directory: ~/repo
    docker:
        - image: circleci/node:7.10
    steps:
        - checkout
        - run:
            name: Deploy to Heroku
            command: |
                if [ $CIRCLE_BRANCH == 'master' ]; then
                    git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git master
                fi
                if [ $CIRCLE_BRANCH == 'dev' ]; then
                    git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME_DEV}.git master
                fi

  deploy_feature_all:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Deploy feature* to Heroku/dev
          command: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME_DEV}.git master

workflows:
  version: 2
  build_feature_deploy:
    jobs:
      - build
      - deploy_feature_all:
          requires:
            - build
          filters:
            branches:
              only : /feature-.*/

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy_prod_dev:
#           requires:
#             - build
